apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deployment
  namespace: bankapp-ns
  labels:
    app: bankapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
      - name: bankapp-container
        image: zeeshankanuga/bankapp:latest


        env:
          - name: SPRING_DATASOURCE_URL
            valuefrom:
            configMapKeyRef:
              name: bankapp-configmap
              key: datasource-url
          - name: SPRING_DATASOURCE_USERNAME
            valuefrom:
              configMapKeyRef:
                name: bankapp-configmap
                key: datasource-username
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: bankapp-configmap
                key: mysql-database

          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bankapp-db-secret
                key: db-password

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080