apiVersion: v1
kind: Secret
metadata:
  name: bankapp-db-secret
  namespace: bankapp-ns
  labels:
    app: mysql
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3JkCg==  # Base64 encoded value of "rootpassword"
  db-password: cm9vdHBhc3N3b3JkCg==  # Base64 encoded value of "rootpassword"