apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deployment
  namespace: mysql-ns
  labels:
    app: bankapp
spec:
  selector:
    matchLabels:
      app: bankapp
  replicas: 2
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: zeeshankanuga/bankapp:latest
          ports:
          - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap 
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret 
                  key: SPRING_DATASOURCE_PASSWORD

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: SPRING_DATASOURCE_URL

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_DATABASE


