apiVersion: v1
kind: ConfigMap
metadata: 
  name: mysql-configmap
  namespace: mysql-ns
  labels:
    app: mysql

data: 
  MYSQL_DATABASE: mysql-new-db
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-svc.mysql-ns.svc.cluster.local:3306/mysql-new-db
